"""The database seam: SQLite by default, Postgres by connection string.

Self-hosting keeps its contract — no setting, no server, one SQLite file in
the data directory, exactly as before. Setting `ALPHADESK_DATABASE_URL` (or
the conventional `DATABASE_URL`) to a postgres:// string moves the whole
store to Postgres, which is what a serverless deployment (Cloud Run — no
durable local disk) and the multi-user direction need.

This is deliberately an ADAPTER, not an ORM: store.py keeps writing plain
SQL, and the two engines meet in the middle —

- Statements are written in the shared modern dialect (ON CONFLICT upserts,
  parameterized everything); the adapter only translates the placeholder
  style (`?` -> `%s`) and two DDL spellings for Postgres.
- Rows come back dict-addressable from both engines.
- Connections are context managers with commit-on-success semantics either
  way; the Postgres one also closes (SQLite's is refcount-collected, and
  keeping that behavior identical costs nothing).
- Schema errors raise one shared type, so init()'s idempotent try-ALTER
  migrations stay engine-blind.

The driver is pg8000 — pure Python and BSD-licensed, keeping the project's
every-dependency-permissive guarantee (the common C drivers are LGPL).
"""

from __future__ import annotations

import os
import re
import sqlite3
import threading
from typing import Any, Iterator
from urllib.parse import urlparse


class SchemaError(Exception):
    """One error type for 'that column/table already exists or never did' —
    what init()'s idempotent migrations catch, whichever engine raised it."""


def url() -> str | None:
    raw = (os.environ.get("ALPHADESK_DATABASE_URL")
           or os.environ.get("DATABASE_URL") or "").strip()
    return raw if raw.startswith(("postgres://", "postgresql://")) else None


def backend() -> str:
    return "postgres" if url() else "sqlite"


# ── SQL translation (Postgres side only) ───────────────────────────────────

def _tr(sql: str) -> str:
    """The whole translation layer, kept small enough to read:
    placeholders, and the two DDL spellings the engines disagree on. Our SQL
    contains no literal question marks, which is what makes the placeholder
    swap safe as plain replacement."""
    sql = sql.replace("?", "%s")
    sql = sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT",
                      "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    return sql


# ── Postgres wrappers ──────────────────────────────────────────────────────

class _PgCursor:
    def __init__(self, cur: Any) -> None:
        self._cur = cur

    @property
    def rowcount(self) -> int:
        return self._cur.rowcount

    def _cols(self) -> list[str]:
        return [d[0] for d in (self._cur.description or [])]

    def fetchone(self) -> "_Row | None":
        row = self._cur.fetchone()
        return None if row is None else _Row(zip(self._cols(), row))

    def fetchall(self) -> "list[_Row]":
        cols = None
        out = []
        for row in self._cur.fetchall():
            cols = cols or self._cols()
            out.append(_Row(zip(cols, row)))
        return out

    def __iter__(self) -> "Iterator[_Row]":
        return iter(self.fetchall())


class _Row(dict):
    """Dict-addressable like sqlite3.Row, plus [0]-style access for the odd
    aggregate read."""

    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


class _PgConn:
    def __init__(self, raw: Any) -> None:
        self._raw = raw

    def execute(self, sql: str, params: tuple | list = ()) -> _PgCursor:
        cur = self._raw.cursor()
        try:
            cur.execute(_tr(sql), tuple(params))
        except Exception as exc:
            if _is_schema_error(exc):
                raise SchemaError(str(exc)) from exc
            raise
        return _PgCursor(cur)

    def executemany(self, sql: str, rows: list[tuple]) -> _PgCursor:
        cur = self._raw.cursor()
        if rows:
            cur.executemany(_tr(sql), [tuple(r) for r in rows])
        return _PgCursor(cur)

    def __enter__(self) -> "_PgConn":
        return self

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        try:
            if exc_type is None:
                self._raw.commit()
            else:
                self._raw.rollback()
        finally:
            self._raw.close()


def _is_schema_error(exc: Exception) -> bool:
    text = str(exc)
    # pg8000 surfaces server errors with SQLSTATE codes: 42701 duplicate
    # column, 42P07 duplicate table, 42703/42P01 undefined column/table.
    return bool(re.search(r"'C': '42(701|P07|703|P01)'", text))


def _pg_connect() -> _PgConn:
    import pg8000.dbapi
    u = urlparse(url() or "")
    kwargs: dict[str, Any] = {
        "user": u.username or "postgres",
        "password": u.password,
        "database": (u.path or "/").lstrip("/") or "postgres",
    }
    sock_dir = _qs(u.query, "host")
    if sock_dir:
        # Cloud SQL's convention: ?host=/cloudsql/<project:region:instance>
        # names the socket DIRECTORY; this driver wants the socket FILE, and
        # refuses a TCP host alongside it — exactly one transport.
        kwargs["unix_sock"] = sock_dir.rstrip("/") + "/.s.PGSQL.5432"
    else:
        kwargs["host"] = u.hostname or "localhost"
        kwargs["port"] = u.port or 5432
    return _PgConn(pg8000.dbapi.connect(**kwargs))


def _qs(query: str, key: str) -> str | None:
    from urllib.parse import parse_qs
    vals = parse_qs(query).get(key)
    return vals[0] if vals else None


# ── the one entry point store.py uses ──────────────────────────────────────

# Serializes SQLite writers within this process; harmless coarse-graining on
# Postgres, which handles its own concurrency.
lock = threading.Lock()


def connect(sqlite_path: Any) -> Any:
    if backend() == "postgres":
        return _pg_connect()
    conn = sqlite3.connect(sqlite_path, timeout=15)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row
    return conn


def exec_script(conn: Any, script: str) -> None:
    """The schema, on either engine. Statements in the schema contain no
    embedded semicolons, which is what makes the split safe."""
    if isinstance(conn, _PgConn):
        # Strip line comments BEFORE splitting: the schema's inline prose
        # contains semicolons ("Nasdaq supplies it; a calendar of bare
        # tickers…"), and splitting through one beheads the statement it
        # lives in. Safe because no DDL string literal here contains `--`.
        code = "\n".join(ln.split("--", 1)[0] for ln in script.splitlines())
        for stmt in code.split(";"):
            if stmt.strip():
                conn.execute(stmt)
    else:
        conn.executescript(script)


def table_columns(conn: Any, table: str) -> set[str]:
    """Column names, or empty when the table does not exist — the shape
    init()'s one drop-and-recreate migration checks."""
    if isinstance(conn, _PgConn):
        rows = conn.execute(
            "SELECT column_name FROM information_schema.columns"
            " WHERE table_name = ?", (table,)).fetchall()
        return {r["column_name"] for r in rows}
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return {r["name"] for r in rows}


def schema_errors() -> tuple[type[Exception], ...]:
    """What init()'s idempotent migrations catch: the engine-native error
    for SQLite (raised straight off conn.execute) and the adapter's own
    SchemaError for Postgres."""
    return (sqlite3.OperationalError, SchemaError)
